### ISSUE TITLE
[Suggestion] Resize App

### ISSUE THREAD

**Issue by Smoker1** [Yohoki/TempAR-Vita#4]
Suggest being able to resize the App, so Users can see more of the Paths. Lost my place a couple times last Night.

**Comment by Yohoki** [comment]
Certainly. I actually just did that on another branch. I'm trying to make a code generator, and needed extra space for all the things... I'll push a minor update real quick.

**Comment by Yohoki** [comment]
Try out the newest build - https://github.com/Yohoki/TempAR-Vita/releases/tag/v1.03

**Comment by Smoker1** [comment]
Much better. Least now Users have a bigger Field of View to work with. 
Not sure if it is possible, but would there be a way to filter out Paths that do not contain any Highlighted Results? But if a Path when Double Clicked has a Highlighted Path, it should be kept. Thinking that might require too much, but if it can be done down the road, would be preferred

**Comment by Yohoki** [comment]
Good. I needed the extra space anyway for the next project I'm working on.

It's already on my todo list ( #3 ).  I have NO idea if it's possible how the code is set up. But I also have NO idea what I'm doing lol. I would love this feature and want to get it in, but it will take a lot of studying to get it going, since I don't actually know any C#. Maybe once I get comfortable with it and start actually reading that bit of the code, I'll be able to figure out how to do it. But for now, it's on the back burner.
